# Copyright 2018-2019 the Deno authors. All rights reserved. MIT license.
# Dummy package info required by `cargo fetch`.
# Use tools/sync_rust_crates.py to install deps after editing this file.
# Deno does not build with cargo. Deno uses a build system called gn.
# See build_extra/rust/BUILD.gn for the manually built configuration of rust
# crates.


[[bin]]
name = "deno"
path = "main.rs"

[package]
name = "deno_cli"
version = "0.12.0"
edition = "2018"

[dependencies]
deno = { path = "../core" }

ansi_term = "0.11.0"
atty = "0.2.11"
clap = "2.33.0"
dirs = "2.0.1"
dlopen = "0.1.7"
flatbuffers = "0.6.0"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
futures_01 = { package = "futures", version = "0.1.28" }
http = "0.1.17"
hyper = "0.12.30"
hyper-rustls = "0.16.1"
indexmap = "1.0.2"
integer-atomics = "1.0.2"
lazy_static = "1.3.0"
libc = "0.2.58"
log = "0.4.6"
rand = "0.6.5"
regex = "1.1.7"
remove_dir_all = "0.5.2"
ring = "0.14.6"
rustyline = "4.1.0"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = { version = "1.0.39", features = [ "preserve_order" ] }
source-map-mappings = "0.5.0"
tempfile = "3.0.8"
termcolor = "1.0.4"
tokio = { version = "0.2.0", git = "https://github.com/tokio-rs/tokio", rev = "0d99ddd4f4adfb3ee099a5eefaea529200afcbd1" }
tokio-executor = { version = "0.2.0", git = "https://github.com/tokio-rs/tokio", rev = "0d99ddd4f4adfb3ee099a5eefaea529200afcbd1" }
tokio-fs = { version = "0.2.0", git = "https://github.com/tokio-rs/tokio", rev = "0d99ddd4f4adfb3ee099a5eefaea529200afcbd1" }
tokio-io = { version = "0.2.0", git = "https://github.com/tokio-rs/tokio", rev = "0d99ddd4f4adfb3ee099a5eefaea529200afcbd1" }
tokio-process = { version = "0.2.0", git = "https://github.com/afinch7/tokio-process", rev = "320b8b9bfe77c195a15d14e3f293ade438b7d5c5" }
tokio-threadpool = { version = "0.2.0", git = "https://github.com/tokio-rs/tokio", rev = "0d99ddd4f4adfb3ee099a5eefaea529200afcbd1" }
url = "1.7.2"
utime = "0.2.1"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.7"
fwdansi = "1.0.1"

[target.'cfg(unix)'.dependencies]
nix = "0.13.x"
