# Copyright 2018-2019 the Deno authors. All rights reserved. MIT license.

[package]
name = "test_binding_plugin"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
deno_lib_bindings = { path = "../" }

futures = "0.1.27"