name: Rust

on: [push, pull_request]

jobs:
  pre_checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x 
    - name: Setup
      run: ./tools/setup.py
    - name: Check Format
      run: ./tools/test_format.py
    - name: Lint
      run: ./tools/lint.py
