name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Format
      run: ./tools/test_format.py
    - name: Lint
      run: ./tools/lint.py
